name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *" # run once a night at midnight
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync master branch
        uses: tgymnich/fork-sync@v1.8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          base: master
          head: master
