name: Sync Fork

on:
  push:
    branches:
      - master
  workflow_dispatch: # on button click

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Fetch changes from upstream
        run: git fetch upstream
        env:
          upstream: https://github.com/nf-core/modules.git
      - name: Merge changes from upstream
        run: git merge upstream/master --no-edit
      - name: Push changes to fork
        uses: ad-m/github-push-action@master
        with:
          branch: master