name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  merge:
    runs-on: ubuntu-latest
        steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/nf-core/modules.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Merge upstream master into forked master
        run: |
          git checkout master
          git merge upstream/master --no-edit

      - name: Push changes to forked repository
        run: |
          git push origin master